sudoblockio/icon-tracker-frontend

.gitignore, src/components/CommonPage/TxPage/TxTableBody.js
links to voters addresses were opening on a new tab
=> fix: voters address were opening on new tab #201

src/components/ContractsPage/ContractDetailPage/ContractTabs/ButtonSet.js, src/components/ContractsPage/ContractDetailPage/ContractTabs/ButtonSet.module.css, src/components/ContractsPage/ContractDetailPage/ContractTabs/ContractComponent.js, src/components/ContractsPage/ContractDetailPage/ContractTabs/MiscContractComponents.js, src/components/ContractsPage/ContractDetailPage/ContractTabs/index.js, src/containers/ContractsPage/ContractDetailPageContainer.js, src/redux/actionTypes/actionTypes.js, src/redux/api/jsProvider/icx.js, src/redux/api/restV3/index.js, src/redux/store/contracts.js, src/redux/store/sagas/contractsSaga.js, src/utils/connect.js, src/utils/rawTxMaker/api/custom.js, src/utils/rawTxMaker/index.js
this PR adds full functionality for write methods on contract tab and closes #102
=> full working version of contract tab in contract page

src/libs/txEventParser.js
=> added txEventParser external lib

src/components/ContractsPage/ContractExplorerPage/ContractExplorerPage.module.css, src/components/ContractsPage/ContractExplorerPage/index.js, src/components/ContractsPage/MiscComponents/MiscContractComponents.js, src/config.js, src/redux/api/restV3/config.js, src/redux/api/restV3/icx.js, src/utils/utils.js
Chores: implemented support for custom networks in contract explorer.  feature flagged textarea for the eventlogs in the contract writer. response of write methods is a link back to the tracker, used wireframe 2b without eventlogs
=> multiple chores done

src/components/ContractsPage/ContractDetailPage/ContractTabs/ContractComponent.js, src/components/ContractsPage/ContractExplorerPage/index.js, src/components/ContractsPage/MiscComponents/ButtonSet.js, src/components/ContractsPage/MiscComponents/ButtonSet.module.css
added 'expand' button on contract tab to open contract explorer page with selected contract and network
=> chores: added 'expand' button on contract tab

src/components/ProposalDetailPage/CustomButton.js, src/components/ProposalDetailPage/CustomButton.module.css, src/components/ProposalDetailPage/index.js, src/components/ProposalDetailPage/index.module.css, src/containers/ProposalDetailPage/ProposalDetailPageContainer.js, src/containers/ProposalSubmitPage/ProposalSubmitPageContainer.js
building functionality to vote on network proposals
=> pushing most recent changes

src/components/ContractsPage/ContractExplorerPage/index.js, src/components/ProposalDetailPage/CustomButton.js, src/components/ProposalDetailPage/index.js, src/components/ProposalSubmitPage/index.js, src/redux/store/iiss.js, src/utils/rawTxMaker/api/governance.js
Fixed issues: error calculating date for endBlockheight on network proposals in voting period, fixed steplimit too low to submit network proposals, added variable for testing network detail and network proposal submit page
=> Fixed misc issues

src/components/ProposalDetailPage/CustomButton.js, src/components/ProposalDetailPage/index.js, src/utils/rawTxMaker/api/governance.js
Fixed issues: fixed merge errors on previous commit and steplimit for voting on network proposals
=> Fixed issues

src/components/AddressesPage/AddressDetailPage/AddressTabs/index.js, src/components/AddressesPage/AddressDetailPage/index.js, src/components/BondUpdateModal/bondUpdateModal.js, src/components/BondersUpdateModal/bondersUpdateModal.js, src/components/BondersUpdateModal/bondersUpdateModal.module.css, src/components/CommonComponent/TxBottom/TxBottomComponent.js, src/components/CommonPage/TxPage/TxTableBody.js, src/components/ContractsPage/ContractExplorerPage/index.js, src/components/ContractsPage/MiscComponents/MiscContractComponents.js, src/components/PrepUpdateModal/prepUpdateModal.js, src/components/PrepUpdateModal/prepUpdateModal.module.css, src/components/ProposalDetailPage/CustomButton.module.css, src/redux/api/jsProvider/icx.js
Chore: Updated style in buttons for prep detail and bonders modals, removed button on bonded tab
=> Chore: Fixed misc issues

src/components/AddressesPage/AddressDetailPage/AddressTabs/AddressBonders.js, src/components/AddressesPage/AddressDetailPage/AddressTabs/index.js, src/components/BondUpdateModal/bondUpdateModal.js, src/components/BondUpdateModal/bondUpdateModal.module.css, src/components/BondUpdateModal/customButtonSet.js, src/components/BondUpdateModal/customButtonSet.module.css, src/components/BondersUpdateModal/bondersUpdateModal.js, src/components/CommonComponent/TxBottom/TxBottomComponent.js, src/components/CommonComponent/TxBottom/index.js, src/components/GenericModal/genericModal.js, src/redux/store/iiss.js, src/style/css/common.css, src/utils/rawTxMaker/api/chain.js, src/utils/utils2.js
fixed styles on table tab for address page, created BondUpdateModal
=> Chore: Created modal page for updating bond

src/components/ContractsPage/MiscComponents/MiscContractComponents.js
fixes https://github.com/sudoblockio/icon-tracker-frontend/issues/288
=> chore: fix #288

src/components/GovernancePage/index.js
fix: add reward column to governance table #271
=> fix: add reward column to governance table #271

src/components/TokensPage/TokenDetailPage/TokenTabs/TokenTransactions.js, src/components/TokensPage/TokenDetailPage/TokenTabs/index.js, src/utils/const.js, src/utils/utils.js
Fixed the problem with blank Read Contract.
=> fix: Replace "Read Contract" tab in /token/* view with "Contract" #314

e2e/config.py, e2e/page_objects/address_page.py, e2e/page_objects/token_page.py, e2e/test_cases/address_page_test/test_address_page_token_transfer.py, e2e/test_cases/token_page_test/test_token_read_contract_data.py
Update test cases for token view and also refactor address page title
=> chore: add test cases for token view contract tab

src/components/CommonPage/SearchPage/index.js, src/components/CommonPage/TxPage/index.js, src/components/ProposalListPage/index.js, src/utils/const.js
Updated the cracks in the list functionalities
=> chore: e2e Test cases fails for view list count scenarios #315

src/components/CommonPage/TxPage/index.js
=> fix: pagination button on tx list view

src/components/CommonPage/TxPage/TxTableBody.js, src/components/GovernancePage/index.js
=> fix: Bring back rewards into governance view #341 and Make contracts that delegate linkable #334

src/components/ProposalDetailPage/ApplyButton.js, src/components/ProposalDetailPage/ApplyButton.module.css, src/components/ProposalDetailPage/index.js, src/components/ProposalDetailPage/useProposalPage.js, src/utils/rawTxMaker/api/governance.js
fixed step limit for voting on network proposals and added functionality to apply network proposals
=> fixed #336 and implemented #304

src/components/ProposalDetailPage/index.js, src/components/TokensPage/TokenDetailPage/TokenTabs/TokenEvents.js, src/components/TokensPage/TokenDetailPage/TokenTabs/index.js, src/components/TokensPage/TokenDetailPage/index.js, src/containers/TokensPage/TokenDetailPageContainer.js, src/utils/const.js
=> fix: events tab in token view and date in proposals #83 #302

.gitignore, src/components/AddressesPage/AddressDetailPage/AddressInfo.js, src/components/ContractsPage/ContractDetailPage/ContractTabs/ContractComponent.js, src/components/ContractsPage/contractUtils.js, src/components/PrepUpdateModal/prepUpdateModal.js, src/components/PrepUpdateModal/prepUpdateModal.module.css, src/config.js, src/configData.js, src/redux/store/iiss.js, src/utils/rawTxMaker/api/chain.js, src/utils/rawTxMaker/api/helpers.js
Add request unjail button to validator address page when validator is logged in
=> Add request unjail feature

.gitignore, src/components/AddressesPage/AddressDetailPage/AddressInfo.js, src/components/PrepUpdateModal/prepUpdateModal.js, src/components/PrepUpdateModal/prepUpdateModal.module.css, src/configData.js, src/redux/store/iiss.js, src/utils/rawTxMaker/api/chain.js
New forms for initCommissionRate, setCommissionRate
=> chore: added feature for #363

.gitignore, src/components/AddressesPage/AddressDetailPage/AddressInfo.js, src/components/ContractsPage/contractUtils.js, src/components/PrepUpdateModal/prepUpdateModal.js, src/components/PrepUpdateModal/prepUpdateModal.module.css, src/configData.js, src/redux/store/iiss.js, src/utils/rawTxMaker/api/chain.js, src/utils/rawTxMaker/api/helpers.js
Fixed merge issues, added features for signing initCommissionRate and setCommissionRate for validators, added button for requestUnjail method on validator address page, fix #372 error with methods of type []Address
=> Iiss4 update. Merge fix
